root: true
parser: babel-eslint
extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - babel
  - flowtype
rules:
  import/no-extraneous-dependencies: [2, {}]
  max-len: 0
  import/prefer-default-export: 0
